# Docker Compose override for local development
# This file is automatically included when present

version: '3.8'

services:
  app:
    # Override for development
    command: ["python", "gui/app_simplified.py", "--host", "0.0.0.0", "--port", "5000", "--debug"]
    environment:
      - DEBUG=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      # Add additional development mounts
      - ./logs:/app/logs
      - ./data:/app/data
    # Keep container running for development
    tty: true
    stdin_open: true

  db:
    # Development database with exposed ports
    environment:
      - POSTGRES_DB=hwautomation_dev
    # Mount for database dumps/backups during development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-backups:/backups

  # Additional development services
  adminer:
    image: adminer:latest
    container_name: ${PROJECT_NAME:-hwautomation}-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - hwautomation

  # Redis commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${PROJECT_NAME:-hwautomation}-redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - hwautomation
