# Docker Compose Configuration for HWAutomation
# Production-ready setup with all required services
# Note: version field is deprecated in Docker Compose v2+

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      target: web
    container_name: ${PROJECT_NAME:-hwautomation}-app
    volumes:
      - .:/app
      - /app/hwautomation-env  # Exclude venv from volume mount
      - ./configs:/app/configs:ro  # Mount configs read-only
      - ./data:/app/data  # Mount data directory for databases
      - ./logs:/app/logs  # Mount logs directory
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - HWAUTOMATION_MODE=web
    env_file:
      - .env
    ports:
      - "5000:5000"  # Flask GUI
      - "8000:8000"  # Additional service port
    networks:
      - hwautomation
    # Health check for web application
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  maas-simulator:
    image: maas/maas:latest
    container_name: ${PROJECT_NAME:-hwautomation}-maas-sim
    environment:
      - MAAS_ADMIN_USERNAME=${MAAS_ADMIN_USERNAME:-admin}
      - MAAS_ADMIN_PASSWORD=${MAAS_ADMIN_PASSWORD:-admin123}
    ports:
      - "5240:5240"
    volumes:
      - maas_data:/var/lib/maas
    networks:
      - hwautomation
    profiles:
      - testing  # Only start with --profile testing

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    container_name: ${PROJECT_NAME:-hwautomation}-test
    volumes:
      - .:/app
      - /app/hwautomation-env
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TESTING=1
    env_file:
      - .env
    networks:
      - hwautomation
    profiles:
      - testing
    command: pytest --cov=src/hwautomation --cov-report=xml --cov-report=term-missing

volumes:
  maas_data:

networks:
  hwautomation:
    driver: bridge
