# Logging Configuration for HWAutomation
# This file provides environment-specific logging configurations

version: 1
disable_existing_loggers: false

# Base formatters
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(correlation_id)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    (): hwautomation.logging.config.StructuredFormatter
  
  json:
    (): hwautomation.logging.config.JSONFormatter

# Log filters
filters:
  correlation:
    (): hwautomation.logging.config.CorrelationFilter

# Base handlers
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    filters: [correlation]
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filters: [correlation]
    filename: logs/hwautomation.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    mode: 'a'
    encoding: 'utf-8'
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filters: [correlation]
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    mode: 'a'
    encoding: 'utf-8'

# Logger definitions
loggers:
  hwautomation:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  hwautomation.hardware:
    level: DEBUG
    handlers: [file]
    propagate: true
  
  hwautomation.web:
    level: INFO
    handlers: [console, file]
    propagate: true
  
  hwautomation.orchestration:
    level: INFO
    handlers: [file]
    propagate: true
  
  hwautomation.maas:
    level: INFO
    handlers: [file]
    propagate: true

# Root logger
root:
  level: WARNING
  handlers: [console]

# Environment-specific overrides
environments:
  development:
    handlers:
      console:
        level: DEBUG
        formatter: detailed
      file:
        level: DEBUG
        maxBytes: 5242880  # 5MB
        backupCount: 3
    loggers:
      hwautomation:
        level: DEBUG
      root:
        level: INFO

  staging:
    handlers:
      console:
        level: INFO
        formatter: detailed
      file:
        level: INFO
        maxBytes: 10485760  # 10MB
        backupCount: 5
    loggers:
      hwautomation:
        level: INFO
      root:
        level: WARNING

  production:
    handlers:
      console:
        level: WARNING
        formatter: json
      file:
        level: INFO
        formatter: json
        maxBytes: 52428800  # 50MB
        backupCount: 10
      error_file:
        level: ERROR
        formatter: json
        maxBytes: 52428800  # 50MB
        backupCount: 20
    loggers:
      hwautomation:
        level: INFO
      hwautomation.hardware:
        level: INFO
      hwautomation.web:
        level: WARNING
      root:
        level: ERROR
